# Generated by Django 4.2.1 on 2023-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='languages',
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.ManyToManyField(to='MainApp.language'),
        ),
    ]
